exit <- read.csv('/Users/yimanzhang/Desktop/intern/FSG/FSG_research/NumberofExitvsPass.csv', header=T,stringsAsFactors = F)
head(exit)
str(exit)
levels(exit$name)
exit[,7:11]<- apply(exit[,7:11],2,as.numeric)
exit1 <- exit[!is.na(exit$Maximum_Exit_Score),]
summary(exit1)
exit2 <- exit1[,c(1,2,3,4,5,6,11,12)]
str(exit2)
colnames(exit2)[c(6,7,8)]=c('NumExit', 'MaximumScore','Pass')
model <- glm(factor(Pass) ~ factor(Grade)+factor(NumExit)+factor(Weekly_Assessments_Given),family=binomial(link='logit'),data=exit2)
summary(model)
library('ggplot2')
ggplot(exit2, aes(x=NumExit)) + geom_density()
#model1 <- glm(Pass ~ NumExit+plan_name,family=binomial(link='logit'), data = exit2[exit2$plan_name %in% c('Phonemes','Quantification','Rational Counting','Rhyme','Syllables','Word Awareness',''),])
data1 = exit2[exit2$name %in% c('T1 Rational Counting','T1 Rythm','T1 Word Awareness','T1 One to One'),]
model1 <- glm(factor(Pass) ~ factor(Grade)+factor(NumExit),family=binomial(link='logit'), data = data1)
summary(model1)
model2 <- glm(factor(Pass) ~ factor(Weekly_Assessments_Given),family=binomial(link='logit'),data=data1[data1$Grade=='PS',])
summary(model2)
model3 <- glm(factor(Pass) ~ factor(NumExit),family=binomial(link='logit'),data=data1[data1$Grade=='PS',])
summary(model3)
model4 <- glm(factor(Pass) ~ factor(NumExit),family=binomial(link='logit'),data=data1[data1$Grade=='PK',])
summary(model4)
write.csv(data1,"/Users/yimanzhang/Desktop/data1.csv")
summary(factor(exit1$name))
summary(factor(data1$Grade))
summary(factor(data1$NumExit))

